### ISSUE TITLE
I want to add Java Program for finding age - Age Calculator

### ISSUE THREAD

**Issue by minhaj-313** [Anant-Singh1/HacktoberFest22#8]
Java Program to finding age -
Please assign me under hacktoberfest.
Thank You

**Comment by Anant-Singh1** [comment]
Just create merge request.

**Comment by Anant-Singh1** [comment]
You can create it. But try to add some more function inside it if possible.

**Comment by minhaj-313** [comment]
> You can create it. But try to add some more function inside it if possible.

ok
